name: Update README with Issues

on:
  schedule:
    - cron: '0 22 * * *' # Skripta se pokreće svaki dan u 22:00 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Issues and Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Issues" > README.md
          echo "### Open Issues" >> README.md
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/nrastija/EmbeddedPlayground/issues?state=open" | \
          jq -r '.[] | "- [Issue #" + (.number|tostring) + " - " + .title + "](" + .html_url + ")"' >> README.md
          
          echo "### Closed Issues" >> README.md
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/nrastija/EmbeddedPlayground/issues?state=closed" | \
          jq -r '.[] | "- [Issue #" + (.number|tostring) + " - " + .title + "](" + .html_url + ")"' >> README.md

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Update README with latest issues"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/nrastija/EmbeddedPlayground.git HEAD:main
          else
            echo "No changes to commit"
          fi
